server.port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: root
  jpa:
    show-sql: true
